### ISSUE TITLE
Demo is offline

### ISSUE THREAD

**Issue by maurice-schleussinger** [martinp23/elabchem#7]
http://nitrogen.martinp23.com/elabchem is offline.

**Comment by NicolasCARPi** [comment]
@maurice-schleussinger Martin hasn't been working on this for the past 6 years. You should try [eLabFTW](https://github.com/elabftw/elabftw), it features some tools for chemistry now:

![chemdoodle](http://i.imgur.com/xoTad69.gif)

See: https://www.elabftw.net/
